### ISSUE TITLE
 ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by stewpan** [maminio/dsctl#1]
After connecting with the sparksession and trying to run some jobs, I get:

ModuleNotFoundError: No module named '_bz2'

I suppose bz2 is not installed locally on the server?

**Comment by maminio** [comment]
Thank you for pointing out this issue. 

@Stvdputten Are you using Pandas Dataframe to load your dataset ?

**Comment by stewpan** [comment]
I'm using an RDD e.g.:
data = sc.textFile(path_to_data)

The complete message (sorry for the format):

20/04/12 23:55:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
108413                                                                          
20/04/12 23:55:24 WARN TaskSetManager: Stage 7 contains a task of very large size (1467 KB). The maximum recommended task size is 100 KB.
PythonRDD[8] at RDD at PythonRDD.scala:53
20/04/12 23:55:25 WARN TaskSetManager: Stage 8 contains a task of very large size (1467 KB). The maximum recommended task size is 100 KB.
20/04/12 23:55:25 WARN TaskSetManager: Lost task 2.0 in stage 9.0 (TID 15, 192.168.111.33, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/__init__.py", line 212, in <module>
    from .registry import write, read, sniff, create_format, io_registry
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/registry.py", line 180, in <module>
    from .util import _resolve_file, open_file, open_files, _d as _open_kwargs
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/util.py", line 34, in <module>
    from skbio.io._iosources import get_io_sources, get_compression_handler
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/_iosources.py", line 11, in <module>
    import bz2
  File "/home/s1528459/.local/bin/python3.7/Lib/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:456)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:592)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:575)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:410)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

20/04/12 23:55:26 ERROR TaskSetManager: Task 54 in stage 9.0 failed 4 times; aborting job
Traceback (most recent call last):
  File "script.py", line 67, in <module>
    calculate_rdd(rdd, 5)
  File "script.py", line 61, in calculate_rdd
    combi = it.combinations(dataset_dna.collect(),2)
  File "/home/s1528459/miniconda3/envs/DLNN/lib/python3.7/site-packages/pyspark/rdd.py", line 816, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/home/s1528459/miniconda3/envs/DLNN/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/s1528459/miniconda3/envs/DLNN/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 54 in stage 9.0 failed 4 times, most recent failure: Lost task 54.3 in stage 9.0 (TID 205, 192.168.111.32, executor 3): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/__init__.py", line 212, in <module>
    from .registry import write, read, sniff, create_format, io_registry
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/registry.py", line 180, in <module>
    from .util import _resolve_file, open_file, open_files, _d as _open_kwargs
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/util.py", line 34, in <module>
    from skbio.io._iosources import get_io_sources, get_compression_handler
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/_iosources.py", line 11, in <module>
    import bz2
  File "/home/s1528459/.local/bin/python3.7/Lib/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:456)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:592)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:575)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:410)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1878)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2112)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:990)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:989)
        at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
        at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 364, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/worker.py", line 69, in read_command
    command = serializer._read_with_length(file)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 173, in _read_with_length
    return self.loads(obj)
  File "/home/s1528459/.local/bin/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 587, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/__init__.py", line 212, in <module>
    from .registry import write, read, sniff, create_format, io_registry
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/registry.py", line 180, in <module>
    from .util import _resolve_file, open_file, open_files, _d as _open_kwargs
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/util.py", line 34, in <module>
    from skbio.io._iosources import get_io_sources, get_compression_handler
  File "/home/s1528459/.local/bin/python3.7/lib/python3.7/site-packages/skbio/io/_iosources.py", line 11, in <module>
    import bz2
  File "/home/s1528459/.local/bin/python3.7/Lib/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:456)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:592)
        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRunner.scala:575)
        at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:410)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
        at org.apache.spark.InterruptibleIterator.to(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
        at org.apache.spark.InterruptibleIterator.toBuffer(InterruptibleIterator.scala:28)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
        at org.apache.spark.InterruptibleIterator.toArray(InterruptibleIterator.scala:28)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$15.apply(RDD.scala:990)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

20/04/12 23:55:26 WARN TaskSetManager: Lost task 25.2 in stage 9.0 (TID 194, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 10.3 in stage 9.0 (TID 228, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 22.3 in stage 9.0 (TID 224, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 58.3 in stage 9.0 (TID 197, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 3.3 in stage 9.0 (TID 249, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 51.3 in stage 9.0 (TID 250, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 32.3 in stage 9.0 (TID 221, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 60.3 in stage 9.0 (TID 247, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 15.2 in stage 9.0 (TID 196, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 57.3 in stage 9.0 (TID 243, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 4.3 in stage 9.0 (TID 220, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 9.3 in stage 9.0 (TID 241, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 14.3 in stage 9.0 (TID 200, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 30.3 in stage 9.0 (TID 215, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 49.2 in stage 9.0 (TID 185, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 55.3 in stage 9.0 (TID 251, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 48.3 in stage 9.0 (TID 245, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 11.2 in stage 9.0 (TID 198, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 38.3 in stage 9.0 (TID 219, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 33.2 in stage 9.0 (TID 179, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 12.2 in stage 9.0 (TID 184, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 6.3 in stage 9.0 (TID 213, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 16.3 in stage 9.0 (TID 246, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 36.3 in stage 9.0 (TID 244, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 13.3 in stage 9.0 (TID 218, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 59.2 in stage 9.0 (TID 174, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 31.3 in stage 9.0 (TID 248, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 18.3 in stage 9.0 (TID 216, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 52.3 in stage 9.0 (TID 237, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 5.3 in stage 9.0 (TID 240, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 53.3 in stage 9.0 (TID 239, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 23.3 in stage 9.0 (TID 236, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 21.3 in stage 9.0 (TID 229, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 7.3 in stage 9.0 (TID 234, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 62.3 in stage 9.0 (TID 225, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 27.3 in stage 9.0 (TID 223, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 8.3 in stage 9.0 (TID 232, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 28.3 in stage 9.0 (TID 226, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 50.3 in stage 9.0 (TID 235, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 63.3 in stage 9.0 (TID 222, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 61.3 in stage 9.0 (TID 231, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 47.3 in stage 9.0 (TID 238, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 19.3 in stage 9.0 (TID 214, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 37.3 in stage 9.0 (TID 230, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 45.3 in stage 9.0 (TID 227, 192.168.111.34, executor 1): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 56.3 in stage 9.0 (TID 242, 192.168.111.33, executor 0): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 43.3 in stage 9.0 (TID 212, 192.168.111.32, executor 3): TaskKilled (Stage cancelled)
20/04/12 23:55:26 WARN TaskSetManager: Lost task 26.3 in stage 9.0 (TID 233, 192.168.111.31, executor 2): TaskKilled (Stage cancelled)

**Comment by maminio** [comment]
Is the file on your cluster ?

**Comment by stewpan** [comment]
Yes?  Or should they be copied to the worker nodes as well?

**Comment by maminio** [comment]
If you have it available on the master node and visible by the jupyter notebook, you must be able to read the file and there's no need to copy to worker nodes.

I had issues with Bzip before, but not for reading file. Also I'm not sure about Conda's python build procedure and libraries. 
You can build BZip from source and recompile python. 

```
curl -OL  wget https://sourceware.org/pub/bzip2/bzip2-1.0.6.tar.gz
tar -xf bzip2-1.0.6.tar.gz
cd bzip2-1.0.6.tar.gz
make install PREFIX=<PATH_TO_YOUR_CURRENT_DIR>
# And then recompile python. 
```

Another quick fix would be reading the files in a different way if possible( python's built-in readfile) and pass it as buffer stream to your Spark session.

I will look for a better solution to fix this issue.
